name: Build

on:
  push:
  pull_request:

jobs:
  Windows:
    runs-on: windows-latest

    steps:
    # Checks-out
    - uses: actions/checkout@v2

    - uses: ilammy/msvc-dev-cmd@v1

    #don't use run-cmake for windows because only one build should add warnings to pull request
    - name: Build Debug
      run: |
        mkdir debug
        cd debug
        cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug ..
        nmake

    - name: Upload ryzenadj debug
      uses: actions/upload-artifact@v2
      with:
        name: ryzenadj-win64-debug
        path: |
          debug/ryzenadj.exe
          debug/libryzenadj.dll

    - name: Build Release
      run: |
        mkdir build
        cd build
        cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
        nmake

    - name: Prepair Release Folder
      run: |
        mkdir release
        copy build/ryzenadj.exe release/
        copy build/libryzenadj.dll release/
        copy win32/* release/
        copy examples/* release/

#    - name: Test Scripts
#      shell: pwsh
#      run: |
#        cd release
#        $expectedOutput = "Not AMD processor, must be kidding"
#        $cmdDemoOutput = '' | cmd.exe /c .\demo.bat
#        if ($cmdDemoOutput -notcontains $expectedOutput){
#            Write-Error "$cmdDemoOutput"
#            exit 1
#        }
#        $psServiceOutput = Powershell .\readjustService.ps1 -noGUI
#        if ($psServiceOutput -ne $expectedOutput){
#            Write-Error "$psServiceOutput"
#            exit 1
#        }
#        $pythonOutput = python pmtable-example.py
#        if ($pythonOutput -notcontains $expectedOutput){
#            Write-Error "$pythonOutput"
#            exit 1
#        }
#        $pythonOutput = python readjust.py
#        if ($pythonOutput -notcontains $expectedOutput){
#            Write-Error "$pythonOutput"
#            exit 1
#        }
#        exit 0

    - name: Upload ryzenadj
      uses: actions/upload-artifact@v2
      with:
        name: ryzenadj-win64
        path: |
            release/
            !release/*.lib
            !release/*.exp

    - name: Upload libryzenadj
      uses: actions/upload-artifact@v2
      with:
        name: libryzenadj-win64
        path: |
            ./build/libryzenadj.dll
            ./build/libryzenadj.lib
            ./lib/ryzenadj.h
            ./win32/inpoutx64.dll
            ./win32/WinRing0x64.dll
            ./win32/WinRing0x64.sys

  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libpci-dev

    - name: run-cmake #with support for inline error reporting
      uses: lukka/run-cmake@v3.3

    - name: Test make like readme
      run: |
        mkdir build && cd build
        cmake DCMAKE_BUILD_TYPE=Release ..
        make

#    - name: Test Scripts
#      shell: bash
#      run: |
#        cd examples
#        export LD_LIBRARY_PATH="${{ github.workspace }}/build/"
#        expectedOutput="Not AMD processor, must be kidding"
#        pythonOutput=$(python pmtable-example.py 2>&1) || true
#        if [[ ! "$pythonOutput" =~ "$expectedOutput" ]]; then
#            echo "pmtable-example.py output: $pythonOutput"
#            exit 1
#        fi
#        pythonOutput=$(python readjust.py 2>&1) || true
#        if [[ ! "$pythonOutput" =~ "$expectedOutput" ]]; then
#            echo "readjust.py output: $pythonOutput"
#            exit 1
#        fi
#        exit 0

